### ISSUE TITLE
Broken web search

### ISSUE THREAD

**Issue by fzuccolo** [PyAr/CDPedia#310]
#### Reproduction
Generate a test CDPedia from [latest master][1], run it and search something that will return results.
The web server returns an error and this traceback is shown in the log:

[1]: https://github.com/PyAr/CDPedia/tree/15ce388ec0c12b7585bde5ce0aad7093de53b7a8

```
127.0.0.1 - - [08/Sep/2020 16:56:22] "POST /search HTTP/1.1" 302 -
127.0.0.1 - - [08/Sep/2020 16:56:22] "GET /search/a HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/fede/cdpedia_project/venv_py38/lib/python3.8/site-packages/werkzeug/middleware/shared_data.py", line 260, in __call__
    return self.app(environ, start_response)
  File "/home/fede/cdpedia_project/cdpedia/src/web/web_app.py", line 271, in wsgi_app
    response = self.dispatch_request(request)
  File "/home/fede/cdpedia_project/cdpedia/src/web/web_app.py", line 256, in dispatch_request
    return getattr(self, 'on_' + endpoint)(request, **values)
  File "/home/fede/cdpedia_project/cdpedia/src/web/web_app.py", line 209, in on_search_results
    sorted_results = self.searcher.get_grouped(id_, start, quantity)
  File "/home/fede/cdpedia_project/cdpedia/src/web/searcher.py", line 162, in get_grouped
    for link, title, ptje, original, text in results:
ValueError: too many values to unpack (expected 5)
```
#### Cause

The problem is that each index result contains 6 items, but only 5 are expected:

https://github.com/PyAr/CDPedia/blob/15ce388ec0c12b7585bde5ce0aad7093de53b7a8/src/web/searcher.py#L162

This is caused by a duplicated `score` parameter when generating index entries:

https://github.com/PyAr/CDPedia/blob/15ce388ec0c12b7585bde5ce0aad7093de53b7a8/src/armado/compressed_index.py#L536

The `score` was already present in `data`, resulting e.g. in:

```
value = ['P/o/r/Portal:Portada', 'Portal:Portada', 104572, True, '', 104572]
```

#### Possible solution

Removing `+ [score]` fix the issue but breaks some tests related to new index API.

**Comment by fzuccolo** [comment]
Solucionado con #322.
